### PR TITLE
(GH-26) Implement Gulp

### PR DESCRIPTION
**Pull request by designxsteph**
Introduces gulp.js to handle bundling and minification of assets.
All scss/css/js are now housed in a centralized repository and
installed via npm. From there the assets are copied and placed in
their respective places after they have been processed by Gulp.

A few files have been added to the .gitignore since they will now be
compiled at runtime, and do not live in this repository.

### CODE REVIEW

**Comment by designxsteph** [comment]
I will update when this is ready to go. I will need to make sure the choco-theme repository is up to date.

**Comment by designxsteph** [comment]
@gep13 This is ready to be pulled in/discussed. I am still working on a README on how to edit the css/js locally, but everything is up to date in theme repository. If you build in `npm install` and then `gulp` in the beginning of the the cake build process, it should all just work on deployment.

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@designxsteph going to take this for a spin, and to get the Cake build updated.

**Pull request merged**
