### PR TITLE
(ENGTASKS-3807) (doc) Add documentation of new rule CPMR0075

### PR DESCRIPTION
**Pull request by AdmiringWorm**
## Description Of Changes

We are planning to implement a new requirement rule for blacklisting URLs that come from GitHub comments. As this is a new rule without any associated documentation, we need to create the documentation that is related to this rule.

## Motivation and Context

New rules should be fully documented.

## Testing

* [x] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

~* [ ] Minor documentation fix (typos etc.).~
~* [ ] Major documentation change (refactoring, reformatting or adding documentation to existing page).~
* [x] New documentation page added.
~* [ ] The change I have made should have a video added, and I have raised an issue for this.~

## Change Checklist

~* [ ] Requires a change to menu structure (top or left-hand side)/~
~* [ ] Menu structure has been updated~

## Related Issue

N/A

### CODE REVIEW

**Comment by pauby** [comment]
LGTM! Thanks for adding this @AdmiringWorm. I'll leave the merging to be done once the rule is in place.

**Comment by gep13** [comment]
Just a quick question on this....

Is it worth showing an example of a GitHub comment URL, so that it is clear what is being picked up on?

**Comment by pauby** [comment]
I think that would be a good addition.

**Comment by AdmiringWorm** [comment]
I have created the PR https://github.com/chocolatey/docs/pull/1032 to include that inormation.

**Pull request merged**
