### PR TITLE
(#81) Add CCM Deployments API worked example

### LINKED ISSUE #81: Add CCM Deployments worked API example
As a reference resource, we could use some worked examples for the API. I have one I prepped for the CCM 0.4.0 webinar during 2020 12 Days of Chocolatey that we should add here as a starting point.

### PR DESCRIPTION
**Pull request by vexx32**
Added a worked example with a brief description for the CCM Deployments API endpoints (and some related auxiliary endpoints needed for the example).

Resolves #81

### CODE REVIEW

**Review by ferventcoder — APPROVED** [review]
This LGTM!!

**Comment by ferventcoder** [comment]
If I click merge we'll see it live and make any changes right?

**Comment by designxsteph** [comment]
@ferventcoder yes clicking merge will trigger a build/deployment.

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@vexx32 thanks for getting this added!

**Comment by gep13** [comment]
> @ferventcoder said...
If I click merge we'll see it live and make any changes right?

Just to expand a little bit on what @designxsteph said...

> @designxsteph said...
yes clicking merge will trigger a build/deployment.

Merging a PR into the master branch, or directly adding a commit into the master branch, will trigger the `Publish Documentation` [GitHub Action](https://github.com/chocolatey/docs/actions) to run.  To all intents and purposes, this is exactly the same as the `Build Pull Request` GitHub Action, with the one difference that it also publishes the site.

If the `Build Pull Request` GitHub action succeeds, which it did here, then there should be no reason that the `Publish Documentation` GitHub Action won't work, unless there is something wrong with git/GitHub.

Once the main portion of the build completes, the artifacts of the Statiq build are committed into the gh-pages branch of this repository, and after a short delay, the pages will be served ready for viewing.  There may still be some Cloudflare caching in action, so you might not see any changes immediately, unless we bust the necessary pages from Cloudflare.

**Comment by gep13** [comment]
@vexx32 @ferventcoder @designxsteph this change is now live on the site: https://docs.chocolatey.org/en-us/central-management/usage/api

**Pull request merged**
