### PR TITLE
(GH-6)(theme) Minor Layout Adjustments and Search Updates

### PR DESCRIPTION
**Pull request by designxsteph**
In this PR:

* Moves the "Edit this page" link to the top of the right nav instead of the bottom
* Decreases spacing in left side navigation links
* Switches the search from opening in a modal, to opening in a popover in place

### CODE REVIEW

**Review by gep13 — APPROVED** [review]
LGTM

**Comment by gep13** [comment]
@designxsteph thanks for getting this updated!

**Review by ferventcoder — COMMENTED** [review]
👍

**Comment by designxsteph** [comment]
Note: There are currently a few issues with the mobile search, but fixing it up in my next PR.

**Pull request merged**
