### PR TITLE
Add Cloudsmith to docs as an alternative Package Manager to host Choc…

### PR DESCRIPTION
**Pull request by ciaracarey**
…olatey packages

### CODE REVIEW

**Review by steviecoaster — APPROVED** [review]
LGTM

**Comment by steviecoaster** [comment]
Trigger the GHA for this contribution. PR didn't touch the workflow, so safe to do.

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@ciaracarey thanks for taking the time to get this added.  Assuming the CI build passes, we can get this merged into the production site.

**Review by gep13 — APPROVED** [review]
LGTM!

**Pull request merged**
