### PR TITLE
(doc) Remove Nexus issue link as it's no longer accessible

### PR DESCRIPTION
**Pull request by pauby**
## Description Of Changes
Removed the link to the [Nexus infinite paging issue](https://issues.sonatype.org/browse/NEXUS-13426) as it no longer exists (even after logging in).

## Motivation and Context
The link is no longer accessible.

## Testing
N/A - this was just removing a link from the markdown.

## Change Types Made

* [x] Minor documentation fix (typos etc.).
* [ ] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [ ] New documentation page added.
* [ ] The change I have made should have a video added, and I have raised an issue for this.

## Change Checklist

* [ ] Requires a change to menu structure (top or left hand side)
* [ ] Menu structure has been updated

## Related Issue
N/A

### CODE REVIEW

**Review by steviecoaster — APPROVED** [review]
LGTM

**Comment by steviecoaster** [comment]
@pauby this needs rebased and then I can merge it.

**Comment by pauby** [comment]
@steviecoaster That's been rebased now.

**Comment by gep13** [comment]
@pauby Thanks for getting that removed!

**Pull request merged**
