### PR TITLE
(maint) Apply scripting best practices

### PR DESCRIPTION
**Pull request by pauby**
## Description Of Changes
I have made some changes based on best practices guide.

## Motivation and Context

We should apply our own recommendations to our scripts.

## Testing

* [x] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* [ ] Minor documentation fix (typos etc.).
* [x] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [ ] New documentation page added.
* [ ] The change I have made should have a video added, and I have raised an issue for this.
    * Issue #

## Change Checklist

* [ ] Requires a change to menu structure (top or left hand side)/
* [ ] Menu structure has been updated

## Related Issue

N/A

### CODE REVIEW

**Review by gep13 — DISMISSED** [review]
LGTM

**Comment by gep13** [comment]
@pauby are you able to resolve the conflicts here? I am on phone just now, but could take a look later.

**Comment by pauby** [comment]
Let me take a look later @gep13

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@pauby thanks for getting this fixed up!

**Comment by pauby** [comment]
I've now fixed that up.

**Comment by gep13** [comment]
I literally just pushed up some changes as well...

Let me re-review.

**Review by gep13 — APPROVED** [review]
LGTM!

**Pull request merged**
