### PR TITLE
(maint) Add video check for changes

### PR DESCRIPTION
**Pull request by pauby**
## Description Of Changes
Added a check to the PR template to remind us that a video of any changes could be made and added to the page. If that is the case, we should raise an issue so we don't forget to create it, and add that issue number to the PR.

## Motivation and Context
It was suggested by @steviecoaster that we add more video to our docs and adding a check in the PR template is a good way for us to remember to do this.

## Testing

* [x] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* [x] Minor documentation fix (typos etc.).
* [ ] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [ ] New documentation page added.

## Change Checklist

* [ ] Requires a change to menu structure (top or left hand side)/
* [ ] Menu structure has been updated

## Related Issue

N/A

### CODE REVIEW

**Comment by pauby** [comment]
@gep13 as you make a lot of the videos for the docs, I wanted to get your input.

**Comment by pauby** [comment]
@AdmiringWorm Can we look to add a 'Video' label (or something similar) to the workflow in the .github repository to have it sync here?

**Comment by AdmiringWorm** [comment]
> @AdmiringWorm Can we look to add a 'Video' label (or something similar) to the workflow in the .github repository to have it sync here?

Will that label be useful for all the other repositories we have (or most)?
If so, yes, that could be easily added. If it would just be for this repository, I would suggest that we add another specific configuration file in this repository once we have the file sync in place (we can have multiple configuration files).

**Comment by pauby** [comment]
I think it would just be here @AdmiringWorm

**Review by gep13 — APPROVED** [review]
LGTM!

**Pull request merged**
