### PR TITLE
(doc) Add link to C4B Azure offer

### PR DESCRIPTION
**Pull request by pauby**
## Description Of Changes
Add a link to the Azure Marketplace offer for C4B.

## Motivation and Context
The summary doesn't contain a link to the offer. I had to keep reading to find it.

## Testing

* [ ] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* [x] Minor documentation fix (typos etc.).
* [ ] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [ ] New documentation page added.

## Change Checklist

* [ ] Requires a change to menu structure (top or left hand side)/
* [ ] Menu structure has been updated

## Related Issue

N/A

### CODE REVIEW

**Comment by Windos** [comment]
@pauby should we be linking directly or via the short URL (`https://ch0.co/C4B-Azure`)?

**Comment by pauby** [comment]
@windows The Short URL makes sense. I took that link from the doc page. Let me update this.

**Comment by gep13** [comment]
@pauby wanted to ping you about this. Is this something you want to move forward with?

**Comment by Windos** [comment]
@gep13, thinking aboutt his one there are a few other instance where the longer URL is used that we could probably change to the short URL.

I'd say this can be merged, as it's consistent with the existing docs.

An issue can be created for changing any links to short links, where this makes sense to do so, in one go.

**Review by gep13 — APPROVED** [review]
LGTM!

**Pull request merged**
