### PR TITLE
(#388) Add .github templates

### LINKED ISSUE #388: Create .github templates
The [standard templates for the Chocolatey organization](https://github.com/chocolatey/.github) has information not relevant to this repository. We should create templates specifically for here.

### PR DESCRIPTION
**Pull request by pauby**
## Description Of Changes
Added relevant .github templates.

## Motivation and Context
The [standard templates for the Chocolatey organization](https://github.com/chocolatey/.github) has information not relevant to this repository.

## Testing
No testing was done.

## Change Types Made

* [ ] Bug fix (non-breaking change)
* [x] Feature / Enhancement (non-breaking change)
* [ ] Breaking change (fix or feature that could cause existing functionality to change)
* [ ] PowerShell code changes.

## Related Issue

Fixes #388 

## Change Checklist

* [ ] Requires a change to the documentation
* [ ] Documentation has been updated
* [ ] Tests to cover my changes, have been added
* [ ] All new and existing tests passed.
* [ ] PowerShell v2 compatibility checked.

[Clickup Task](https://app.clickup.com/t/20540031/ENGTASKS-577)

### CODE REVIEW

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@pauby I enabled Discussions on this repository just now, as this hadn't been done, and we were linking to discussions from the config.yml file.

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@pauby having merged this, and seen it in action (this wasn't possible until the merge happened), am I not right in saying that we have a duplication of things here:

image

Do we need both?

**Comment by pauby** [comment]
Thanks for catching that. I'll pick this up outside the PR.

**Pull request merged**
