### PR TITLE
(#494) Add Release Notes Videos

### LINKED ISSUE #494: Add Release Note Videos From Gary Park
## What New Or Updated Would You Like To See?

Add the recently release note videos Gary Park has put out on his YouTueb channel to the release note docs.

## Why Is It Needed?

Adds a visual and audio recap of the contents of the release notes for user of the product.

### PR DESCRIPTION
**Pull request by ryanrichter94**
## Description Of Changes
Add the recent release notes videos Gary published to his Youtube channel.

## Motivation and Context
Is a nice reference our customers have become accustom to having. 

## Testing

* [X] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* [ ] Minor documentation fix (typos etc.).
* [X] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [ ] New documentation page added.

## Change Checklist

* [ ] Requires a change to menu structure (top or left hand side)/
* [ ] Menu structure has been updated

## Related Issue

Fixes #494

### CODE REVIEW

**Review by gep13 — CHANGES_REQUESTED** [review]
On the whole, this is great PR, thanks so much for getting this done. I do think we need a slight change here though.

**Comment by gep13** [comment]
If you look at some of the other videos that are added, you will see that they use the following:

```
<iframe src="https://www.youtube.com/embed/py-3BJIPebk?list=PLGvGJzqY88sm2CQ1Bf5ZGCgtJbTlgw1xK" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen>
```

where as for the new ones that you have added, you are using this:

```
<iframe src="https://www.youtube.com/embed/wm9FiYRm8mA" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen>
```

What this means is that we _lose_ the playlist section of the video that is displayed, i.e. this:

image

Can you go back and add the playlist to each embedded video? It should be a case of adding `?list=PLGvGJzqY88sm2CQ1Bf5ZGCgtJbTlgw1xK` to each URL.

**Comment by ryanrichter94** [comment]
Thanks for catching and explaining this Gary. I'll get this fixed up.

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@ryanrichter94 I took the opportunity to add the playlist attribute to each video.

Thanks again for getting this added to the release notes pages.

**Pull request merged**
