### PR TITLE
Add link to version number normalisation page

### LINKED ISSUE #1082: Add a link from the 'create packages' page to the 'version normalisation' page
## What New Or Updated Would You Like To See?

Cross reference the Version number normalization page from the Create Package page (under the version number section)

## Why Is It Needed?

Improve awareness of the normalisation stuff

### PR DESCRIPTION
**Pull request by flcdrg**
## Description Of Changes

Add link to the Version Number Normalization page

## Motivation and Context

Relates to this section of the docs

## Testing

* [x] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* [x] Minor documentation fix (typos etc.).
* [ ] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [ ] New documentation page added.
* [ ] The change I have made should have a video added, and I have raised an issue for this.
    * Issue #

## Change Checklist

* [ ] Requires a change to menu structure (top or left-hand side)/
* [ ] Menu structure has been updated

## Related Issue

Fixes #1082

### CODE REVIEW

**Comment by pauby** [comment]
@flcdrg awesome work! Thanks for your contribution!

**Comment by flcdrg** [comment]
Just need someone to approve this :-)

**Review by corbob — APPROVED** [review]

**Comment by corbob** [comment]
> Just need someone to approve this :-) 

I think Paul intended to approve it and instead just enabled the auto merge. I've approved it. Thanks for the contribution @flcdrg 👍

**Comment by pauby** [comment]
I did. I usually remind myself to go back and check it happened. Must have missed this one. Apologies.

**Pull request merged**
