### PR TITLE
(#83) Move API examples to subpage

### PR DESCRIPTION
**Pull request by vexx32**
To make the examples easier to find:

- Created API subsection and moved current API page to section index
- Created examples page in new section and moved examples content over

### CODE REVIEW

**Review by ferventcoder — CHANGES_REQUESTED** [review]
Would you mind leaving `## Examples` and then linking to the subpage? Thanks in advance

**Comment by gep13** [comment]
@ferventcoder I went to add an additional section in the docs as you suggested, but I actually think that this is not required:

image

There is already a Child Pages section displayed at the bottom of the page.

I am going to merge "as-is" for just, and if we want to add this extra section in, we can.

**Comment by gep13** [comment]
@ferventcoder perhaps we move this `## Examples` section to higher in the document, so that they aren't right beside each other?

**Comment by gep13** [comment]
@vexx32 I made a couple [changes](https://github.com/chocolatey/docs/pull/84/commits/40d01ce791ba5217082a54c2f5a4c988cdc72980) to the front matter for the new page along with some explanations as to why.  Let me know if you have any questions.

**Pull request merged**
