### PR TITLE
(doc) Clarify MSI purpose

### LINKED ISSUE #808: Add a page about the MSI that can be used for installing Chocolatey CLI
## What New Or Updated Would You Like To See?

Add a page with information on the Chocolatey CLI MSI.

## Why Is It Needed?

We now build an MSI, it would be good to have a page that we can link to with some information about the CLI.

## Additional Context?

We should ensure to include information about the known exit codes and what they mean. In particular that 1603 during an upgrade is most likely that you can't upgrade with the MSI.

We should also update the ShortURL `https://ch0.co/cli-msi` to point to this new page once it is published.

### PR DESCRIPTION
**Pull request by pauby**
## Description Of Changes
Clarifies the purpopse of the MSI and that it is only for installing Chocolatey CLI.

## Motivation and Context
Clarification is needed.

## Testing

* [x] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* [ ] Minor documentation fix (typos etc.).
* [x] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [ ] New documentation page added.
* [ ] The change I have made should have a video added, and I have raised an issue for this.
    * Issue #

## Change Checklist

* [ ] Requires a change to menu structure (top or left-hand side)/
* [ ] Menu structure has been updated

## Related Issue

Fixes #808

### CODE REVIEW

**Comment by gep13** [comment]
I think the line endings of this file change in this PR, was this intentional?

**Comment by pauby** [comment]
Nope! And my bad for not checking the PR here. The PR in the editor just shows 4 line change.

**Comment by corbob** [comment]
> What would the line endings be? Do we not enforce that anywhere?

@pauby it looks like the editorconfig sets the line endings for all files to LF: https://github.com/chocolatey/docs/blob/master/.editorconfig

Assuming your editor has a plugin for editorconfig, or honors it, then it seems likely that is what changed the file (I've checked, and the file is CRLF on the master branch, and LF here).

**Review by corbob — CHANGES_REQUESTED** [review]
This change looks good to me. The only change I would request is to split the commit into the correcting of the line endings on one commit, and the actual change onto another commit.

**Comment by pauby** [comment]
Apologies @corbob. I asked you to review this completely forgetting it had issues!    🤦

**Comment by pauby** [comment]
@corbob @gep13 the line endings change has been moved to a separate commit.

**Review by corbob — APPROVED** [review]
LGTM!

**Comment by corbob** [comment]
Thanks for getting this added @pauby 👍

**Pull request merged**
