### PR TITLE
(doc) Update info about useRememberedArgumentsForUpgrades feature

### PR DESCRIPTION
**Pull request by soredake**
## Testing

* [x] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* [x] Minor documentation fix (typos etc.).
* [ ] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [ ] New documentation page added.
* [ ] The change I have made should have a video added, and I have raised an issue for this.
    * Issue #

## Change Checklist

* [ ] Requires a change to menu structure (top or left hand side)/
* [ ] Menu structure has been updated

## Related Issue

Fixes #

### CODE REVIEW

**Comment by soredake** [comment]
Several years passed and this feature still not enabled by default, therefore, it would be more logical to remove the information that this feature will be enabled by default in the next release.

**Comment by pauby** [comment]
> in the next release.

The documentation doesn't say it will be switched on in the _next release_.

**Comment by soredake** [comment]
Having note about "future release" when 3+ years passed already is pointless, but it is only my opinion.

**Comment by pauby** [comment]
I don't agree. It will still be a future release.

**Pull request closed without merging**
