### PR TITLE
(GH-23) Add Additional Meta Tags and Organize

### LINKED ISSUE #23: Analyze and improve meta tags
In the head of `_layout.cshtml` there are these meta tags:

```
<meta property="og:title" content="@title" />
<meta property="product:brand" content="Chocolatey" />
<meta property="og:description" content="Chocolatey is software management automation for Windows that wraps installers, executables, zips, and scripts into compiled packages. Chocolatey integrates w/SCCM, Puppet, Chef, etc. Chocolatey is trusted by businesses to manage software deployments." />
<meta name="description" content="Chocolatey is software management automation for Windows that wraps installers, executables, zips, and scripts into compiled packages. Chocolatey integrates w/SCCM, Puppet, Chef, etc. Chocolatey is trusted by businesses to manage software deployments." />
<meta name="flattr:id" content="mqgjkp">
<meta property="DC.title" content="@title" />
<meta property="og:site_name" content="Chocolatey" />
<meta property="og:type" content="product" />
<meta property="product:category" content="software" />
<meta property="og:image" content="https://chocolatey.org/content/images/icon_slogan.png" />
<meta property="og:url" content="@Context.GetLink().TrimEnd('/')@Document.GetLink()" />
<meta property="copyright" content="Chocolatey is Copyright 2020 - @DateTime.UtcNow.Year Chocolatey Software,Inc." />
```

These tags were copied from chocoaltey.org. They need to be analyzed to determine if they are still relevant or if they are outdated (may be a better way of doing it now). There are also other tags that could be added. For example, Twitter has its own set of tags that would optimize the sharing experience when our website is tweeted about. See https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started

### PR DESCRIPTION
**Pull request by designxsteph**
Adds a few additional meta tags to optimize how this website is shared
on Twitter.

Useful information:

https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/abouts-cards

Fixes #23

### CODE REVIEW

**Comment by designxsteph** [comment]
Screen Shot 2020-11-04 at 11 27 14 AM

This update should fix our image from getting cut off. This would be good to implement on chocolatey.org as well.

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@designxsteph thanks for getting this updated!

**Comment by gep13** [comment]
@designxsteph the deployment of this PR didn't work as we hit the GitHub API limit, so we will need to wait until later to run the deployment again.

**Comment by gep13** [comment]
@designxsteph this should now be live.

**Pull request merged**
