### PR TITLE
(#862) Deployment to upgrade or uninstall  a piece of Software

### PR DESCRIPTION
**Pull request by st3phhays**
## Description Of Changes
This makes changes to the Software documentation to outline how to
create a Deployment Plan for a piece of Software automatically. There
are two options available on these pages which are to either upgrade or
uninstall the Software.

## Motivation and Context
This is documentation to reflect Chocolatey Central Management 0.12.0

## Testing

* [x] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* [ ] Minor documentation fix (typos etc.).
* [x] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [ ] New documentation page added.
* [ ] The change I have made should have a video added, and I have raised an issue for this.
    * Issue #

## Change Checklist

* [ ] Requires a change to menu structure (top or left hand side)/
* [ ] Menu structure has been updated

## Related Issue
* #862

### CODE REVIEW

**Comment by st3phhays** [comment]
Images needed have been tracked so they can be added later.

**Review by vexx32 — DISMISSED** [review]
This looks good to me once the images are in, thanks for sorting this out 💜

**Comment by st3phhays** [comment]
@gep13 I've made quite a bit of changes to this to include uninstall documentation and remove the mention of it from the Computer Details screen, so it may require another quick look over.

**Review by AdmiringWorm — DISMISSED** [review]
LGTM

**Review by gep13 — DISMISSED** [review]
LGTM!

**Review by gep13 — APPROVED** [review]
LGTM!

**Pull request merged**
