### PR TITLE
(#661) Enable Tabs on Docs

### PR DESCRIPTION
**Pull request by st3phhays**
## Description Of Changes
The update to choco-theme here allows the usage of the Bootstrap Tab component. See the PR below for usage:

https://github.com/chocolatey/docs/pull/224

## Motivation and Context
This will allow us to better organize certain content and make it faster for users to find what they need.

## Testing

* [x] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made
* [ ] Minor documentation fix (typos etc.).
* [ ] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [ ] New documentation page added.
* [ ] The change I have made should have a video added, and I have raised an issue for this.

## Change Checklist

* [ ] Requires a change to menu structure (top or left hand side)/
* [ ] Menu structure has been updated

## Related Issue

- #661 
- https://github.com/chocolatey/choco-theme/issues/304

### CODE REVIEW

**Comment by st3phhays** [comment]
This PR can be tested by pulling down this PR here: https://github.com/chocolatey/docs/pull/224

Navigating to the page with the example tabs should result in the tabs switching when clicked on like they should.

**Review by vexx32 — DISMISSED** [review]
Looks good to me! 😊

**Comment by vexx32** [comment]
@st3phhays do you mind rebasing this one off of master before we merge it?

**Comment by st3phhays** [comment]
@vexx32 This has been rebased!

**Review by vexx32 — APPROVED** [review]

**Pull request merged**
