### PR TITLE
(#588) Fix template doc to show full page

### LINKED ISSUE #588: Documentation for custom templates cut off on docs.chocolatey.org
### What You Are Seeing?

The [guide for managing custom templates as packages ](
 https://docs.chocolatey.org/en-us/guides/create/create-custom-package-templates) ends prematurely with the words "To manage a template as a package, create a new package with the name " " 

### What is Expected?

The sentence/paragraph is completed.   I'm guessing it should have the same text as [here](https://github.com/chocolatey/choco-wiki/blob/master/How-To-Create-Custom-Package-Templates.md#manage-as-templates-as-packages)

### How Did You Get This To Happen?
1. Tried to follow the docs to make a custom choco template.

### System Details

* Running Firefox or Edge browsers in Windows 11

### PR DESCRIPTION
**Pull request by pauby**
## Description Of Changes

Te documentation for creating customer package templates abruptly stops due to Markdown being interpreted as HTML and being broken.

NOTE: I haven't previewed this in Docker container as yet, as my Docker install seems to be broken at the moment. I wanted to get this fixed and the change is minimal.

## Motivation and Context

Page is incomplete.

## Testing

* [ ] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* [x] Minor documentation fix (typos etc.).
* [ ] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [ ] New documentation page added.
* [ ] The change I have made should have a video added, and I have raised an issue for this.
    * Issue #

## Change Checklist

* [ ] Requires a change to menu structure (top or left hand side)/
* [ ] Menu structure has been updated

## Related Issue

Fixes #588

### CODE REVIEW

**Review by corbob — DISMISSED** [review]
LGTM!

**Review by rsmall-apira — APPROVED** [review]
Looks good. Thanks.

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@pauby thanks for getting this fixed up!

**Pull request merged**
