### PR TITLE
(#188) Add example configuration for Windows Defender to VirusScanner docs

### PR DESCRIPTION
**Pull request by steviecoaster**
Adds a complete configuration for using Windows Defender with Virus Scanner to the docs.

### CODE REVIEW

**Review by gep13 — CHANGES_REQUESTED** [review]
LGTM! Only slight change that I would request is that we adhere to scripting best practices, in terms of using named options, and surrounding with double quotes bookending apostrophes. https://docs.chocolatey.org/en-us/choco/commands/#scripting-integration-best-practices-style-guide Once this is done, I think this would be good to get merged in.

**Comment by gep13** [comment]
@steviecoaster you in a position to get this updated?

**Comment by steviecoaster** [comment]
@gep13 I've made the adjustments, if you could give them a look.

**Comment by steviecoaster** [comment]
@gep13 I'm merging this. Docs are an area that we can easily roll-back if needed, but I made the requested changes.

**Pull request merged**
