### PR TITLE
(doc)  ID cannot contain the word chocolatey

### PR DESCRIPTION
**Pull request by pauby**
## Description Of Changes
Adding a note to confirm that package ID's cannot contain the word `chocolatey`.

## Motivation and Context
A package with the name `chocolatey` may give the impression that it is official and supported. While this is known, it's not documented.

## Testing

* [ ] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* [x] Minor documentation fix (typos etc.).
* [ ] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [ ] New documentation page added.
* [ ] The change I have made should have a video added, and I have raised an issue for this.
    * Issue #

## Change Checklist

* [ ] Requires a change to menu structure (top or left hand side)/
* [ ] Menu structure has been updated

## Related Issue

N/A

### CODE REVIEW

**Review by JPRuskin — DISMISSED** [review]
I'm a little surprised we'd leave `choco-` available - it also feels pretty "official"... This is a sensible change, though.

**Comment by pauby** [comment]
We do require the title to day 'Unofficial' if choco is used. Maybe I should add that here too?

**Comment by gep13** [comment]
> @pauby said...
Maybe I should add that here too?

Yes, I think that this would be a good addition as well.

**Comment by pauby** [comment]
@JPRuskin @gep13 I've added that now so this is ready for another review.

**Review by JPRuskin — APPROVED** [review]
LGTM!

**Pull request merged**
