### PR TITLE
Add Documentation for .SkipReducer functionality

### LINKED ISSUE #712: Document .SkipReducer functionality
## What New Or Updated Would You Like To See?

Enhance Package Reducer documentation with the addition of the use of `.SkipReducer` files

## Why Is It Needed?

This is useful for packages that contain portable apps for example where you don't want the binary removed, depending on your configuration

### PR DESCRIPTION
**Pull request by steviecoaster**
## Description Of Changes

Adds documentation for using either `.SkipReducer` or `.SkipReducerFiles`

## Motivation and Context

The availability and usage of these files was previously undocumented.

## Testing

* [x] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* [ ] Minor documentation fix (typos etc.).
* [x] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [ ] New documentation page added.
* [ ] The change I have made should have a video added, and I have raised an issue for this.
    * Issue #

## Change Checklist

* [ ] Requires a change to menu structure (top or left hand side)/
* [ ] Menu structure has been updated

## Related Issue

Fixes #712

### CODE REVIEW

**Review by ryanrichter94 — COMMENTED** [review]
Looks good. Would like to see a per package section added to these 2 parts of the FAQ [Part 1](https://docs.chocolatey.org/en-us/features/package-reducer#how-do-i-turn-this-feature-on) [Part 2](https://docs.chocolatey.org/en-us/features/package-reducer#how-do-i-turn-this-feature-off) that reference to the Package-specific Control of PAckage Reducer heading you added.

**Review by ryanrichter94 — APPROVED** [review]
LGTM

**Comment by Bunos07** [comment]
Auto

**Comment by Bunos07** [comment]
> ## Description Of Changes
> 
> Adds documentation for using either `.SkipReducer` or `.SkipReducerFiles`
> 
> ## Motivation and Context
> 
> The availability and usage of these files was previously undocumented.
> 
> ## Testing
> 
> * [x] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.
> 
> ## Change Types Made
> 
> * [ ] Minor documentation fix (typos etc.).
> * [x] Major documentation change (refactoring, reformatting or adding documentation to existing page).
> * [ ] New documentation page added.
> * [ ] The change I have made should have a video added, and I have raised an issue for this.
>     * Issue #
> 
> ## Change Checklist
> 
> * [ ] Requires a change to menu structure (top or left hand side)/
> * [ ] Menu structure has been updated
> 
> ## Related Issue
> 
> 
> Fixes #712 
> 
>

**Comment by Bunos07** [comment]
Auto

**Review by Bunos07 — APPROVED** [review]
Fix

**Review by Bunos07 — APPROVED** [review]
Plsss

**Pull request merged**
