### PR TITLE
(GH-46)(GH-44)(GH-35) Navigation Updates

### LINKED ISSUE #35: Add global links back to chocolatey.org and community
Links should be added to the navigation somewhere, and possibly in the footer, that lead back to chocolatey.org and to the community.

### LINKED ISSUE #44: Add an alert banner for important announcements
It would be good idea to have an announcement banner built in so that we can display important announcements at the top of the page, much like on chocoltey.org. This banner should be easily removable if there are no announcements.

### LINKED ISSUE #46: Only show child pages in grid if they are visible in the main navigation
Right now, all child pages are shown in the "Child Pages" grid on index pages, even if they are hidden in the navigation. If a page is hidden in the navigation, it should also be hidden in this grid.

### PR DESCRIPTION
**Pull request by designxsteph**
In this PR:

* Adds alert banner
* Adds a global navigation
* Improves accessibility on navigation toggle buttons
* Hides child pages from grid if not shown in nav

Screen Shot 2020-11-03 at 7 51 46 AM

Screen Shot 2020-11-03 at 7 47 50 AM

Fixes #46 
Fixes #44 
Fixes #35

### CODE REVIEW

**Comment by designxsteph** [comment]
@gep13 @ferventcoder I have added an alert banner like on chocolatey.org and it also behaves in the same way. We can remove this by deleting the text, however I left it for now. I posted pictures above of the global nav too.. are there any other links we want in there? The "Community" link points to the packages page.

**Comment by gep13** [comment]
I don’t think we have an issue 48 yet. Was this meant to point at another issue?

**Comment by designxsteph** [comment]
> I don’t think we have an issue 48 yet. Was this meant to point at another issue?

I've fixed this up, should have been #46

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@designxsteph should we have a top level navigation item for `Install`?  Other than that, this looks great to me.  I will wait for @ferventcoder to confirm if he wants any additional top level items, and then we can get this merged in.

**Comment by ferventcoder** [comment]
@designxsteph alert banner is great!

**Comment by ferventcoder** [comment]
>  I have added an alert banner like on chocolatey.org and it also behaves in the same way. We can remove this by deleting the text, however I left it for now. I posted pictures above of the global nav too.. are there any other links we want in there? The "Community" link points to the packages page.

Does it use the same cookie?

**Comment by designxsteph** [comment]
> > I have added an alert banner like on chocolatey.org and it also behaves in the same way. We can remove this by deleting the text, however I left it for now. I posted pictures above of the global nav too.. are there any other links we want in there? The "Community" link points to the packages page.
> 
> Does it use the same cookie?

Yes, I've pushed an update to make it the same, as well as the Cookie Notice banner down at the bottom.

**Comment by designxsteph** [comment]
@ferventcoder are there any additional links you want in the global nav? @gep13 has suggested a link to the install page.

**Comment by designxsteph** [comment]
> > > I have added an alert banner like on chocolatey.org and it also behaves in the same way. We can remove this by deleting the text, however I left it for now. I posted pictures above of the global nav too.. are there any other links we want in there? The "Community" link points to the packages page.
> > 
> > 
> > Does it use the same cookie?
> 
> Yes, I've pushed an update to make it the same, as well as the Cookie Notice banner down at the bottom.

@ferventcoder  @gep13  On this note, it has me thinking.. would it be worth it to have two alert banners? One we can use globally and then one specific to the docs site? Not sure if that would be needed/wanted, but would be an easy addition if so.

**Comment by ferventcoder** [comment]
Install page would be good. Right now, no other global items - more will come up later I'm sure.

**Review by ferventcoder — APPROVED** [review]
This is approved for me.

**Comment by ferventcoder** [comment]
> would it be worth it to have two alert banners? One we can use globally and then one specific to the docs site? Not sure if that would be needed/wanted, but would be an easy addition if so.

It might be for sure! Right now let's go with what we have and approach that once we have a need as you mentioned it would be an easy addition.

**Pull request merged**
