### PR TITLE
(#743) Update list usages in documentation

### PR DESCRIPTION
**Pull request by AdmiringWorm**
## Description Of Changes

The changes made here updates any uses of `choco list`
when the local only parameter is being used.

This requires updating images as well, and introduces the differences
between v2.x and v1.x in tab containers as we are still supporting 1.x
for licensed customers.

## Motivation and Context

We should use the latest code examples and screenshots that is valid for the latest version of our products, at the same time as we support business users on older versions we need to provide both.

## Testing

* [x] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

~* [ ] Minor documentation fix (typos etc.).~
* [x] Major documentation change (refactoring, reformatting or adding documentation to existing page).
~* [ ] New documentation page added.~
~* [ ] The change I have made should have a video added, and I have raised an issue for this.~
    ~* Issue #~

## Change Checklist

~* [ ] Requires a change to menu structure (top or left hand side)/~
~* [ ] Menu structure has been updated~

## Related Issue

#743

### CODE REVIEW

**Comment by gep13** [comment]
@AdmiringWorm you mention that this is a work in progress, is this still the case, or is this ready for review/merge?

**Comment by gep13** [comment]
> @AdmiringWorm said...
The only thing I can see that I need to update in this PR is related to the tab containers before it can be merged.

Sounds good.  I am happy to do a final review once this has been completed.

**Comment by AdmiringWorm** [comment]
@gep13 I had a quick look again on this one, and I found out why it is a WIP.

There is quite a bit of images that needs to be updated, and I haven't updated those in this PR yet.

**Comment by AdmiringWorm** [comment]
I have taken this out of draft, and updated what I could.

There are still 2 images, and 1 video left that still show the usage of `--local-only`.
As such, the associated issue cannot be closed, I'll update that issue with the location of these as I do not have the necessary tools installed to create/update these images and video.

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@AdmiringWorm thanks for getting this fixed up!

**Pull request merged**
