### PR TITLE
#308 Fixes badly documented softwareName

### LINKED ISSUE #308: Undocumented softwareName parameter in package function examples
### What You Are Seeing?
The online documentation for multiple Chocolatey PowerShell packaging functions include examples referencing a `softwareName` parameter that isn't explained in those functions' documentation.

At a minimum, the following documentation pages are affected:
https://docs.chocolatey.org/en-us/create/functions/install-chocolateypackage
https://docs.chocolatey.org/en-us/create/functions/install-chocolateyinstallpackage

This implies that there is either an undocumented `softwareName` parameter supported by these functions, or that the examples confusingly include use of unsupported parameters.

### What is Expected?
All supported parameters should be documented.
No example should depict use of unsupported parameters.

### How Did You Get This To Happen? (Steps to Reproduce)
Consulted URLs above.

### Output Log

<details>
<summary>Full Log Output</summary>

<p>

~~~sh
N/A
~~~

</p>

</details>

### PR DESCRIPTION
**Pull request by C0smin**
## Description Of Changes
This change removes all examples that mention `softwareName` as this is not used in code.

## Motivation and Context
Created this PR because I would like to improve the documentation with true to life examples.

## Testing
* [x] No testing done since this changes do not add any new functionality/feature.

## Change Types Made

* [x] Minor documentation fix (typos etc.).

## Change Checklist

* [ ] Requires a change to menu structure (top or left hand side)/
* [ ] Menu structure has been updated

Fixes #308

### CODE REVIEW

**Comment by gep13** [comment]
@C0smin before we can move forward with this, we would need you to fill in the Pull Request Template that you should have been presented with when you created the PR.

Why exactly is this change required?

**Comment by C0smin** [comment]
@gep13, I updated the PR description. In short I'm trying to make sure that the documentation is up to date.

**Comment by TheCakeIsNaOH** [comment]
@C0smin the `softwareName` parameter is planned to be implemented at some point. See: https://github.com/chocolatey/choco/issues/2513

So the solution to #308 would be to get it implemented into Chocolatey CLI, and add documentation for it.

**Comment by ryanrichter94** [comment]
Added tags to this PR to reflect @TheCakeIsNaOH's last reply that changes in Chocolatey CLI will need made before a docs improvement around the `softwareName` parameter can be made.

**Comment by gep13** [comment]
@C0smin thank you for taking the time to raise this PR.  Based on the existing issue for documenting the parameter #308 and the other existing issue for making use of it chocolatey/choco#2513 I am going to go ahead and close out this PR.

Let me know if you have any questions about why this is being done.

**Pull request closed without merging**
